language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: TuLp4mO/JbLGADPTtI9ZC0o28kOUxVwclvpiU3YxtnDcgtmF5kS1psTV/Fi6bvrOoz2hTdSa3FDc6JysVGpCvakZphSSDM5m/pjuZ59Jr2kWOa8IeBASx9yTKisdGQySrgFHhSj0EfPFhitJs/h9vqGYILPKdoFIcpZoL3kNliStkEEWBMFXaXTGMKcIcWnUz98XwVQzDeqw5BSvpXKKw+3OIrGo8LZygMswJT/E3yjsUQmGULsPUC1h96BD8fJn+THyT8psHM/PUnTweyCVve8+/R2Mr+gFX7kVpno+UvY0/WnXkqfTAZ1HeGypqKRnFj07oMBu2rDznC9g++ssJ6nxUoOVXhUBNnkaHbKXt14g/ZcFZsniPjJ1hAzZPQzI0Cn+3SBA/w374gR5Iemo36DXhGK/saUXUgUlrTXF8iByhEdc28nQSW3O0uKyjXTSwhQtKKchJ9LxtTkC0kSkFzI/7bexXFqupSMKB0HzAKWY7L78jiFfafMPdtvftCaaGSZPs3H9uIBYEFJ+TL77RTKMQD9dnE2Td38hTPQCcxb56GFUVUKxvbCqzGdaEZIExY+zGcG8m/ka+rzw9jv629OrDSYrI/2a5JF6PUiszoNEkNKOnEts11ZL0+uvUYefo34g13iqvx2FDTG3ptmDFG6GxM4ZXrqVi40DhW1jmDU=
  app: Abdeboskey/Todo-Terminal
