language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: RCFhBbAUDejJEzYvqQiD0xL/+rwcVtq082yVAx+dL32xBk0Z+OYrjKY6+43oAH7MxP5iWxOIUnJWJzlHg7skq/BZEKKF8dF20mGCmnT+H8TcfVSie8B/haDsPzdzcfam7dB5H0Arm4cGGon7gwUtwYFDQ1C3ES3zKuwOKovOybGaKlizefpI6zsFo7GHrQNNRx8hJZs/D8exD6ituNW1ADGQdeLTUjJrTLsx90LP8aoZ8tNqZ/QOz/co+N/mkogkN9NPWqImZQwl97q2MLBTFGRmm9phyGzHhCjy/kMTHeuf9Z7JuD54QhpX9FPl2oVgc6Kx9gioy8DS5qGISH8AJKZlITd6TUcEiNHhvv/QP3mIUx8q75ArekOvfTrcUMVtON7ZROi0GZuu9jjSSc9E4/O+UQ5d21brC2mUOqIWC6m7t8ok+vsR5OvjiIbrbSaTdAyUlYBlbB7y8hgmgbyKoYP9iUM/KVEs5fNCiYQAm0MAja5gmVx4RHYYH/qowY6G2QLD/1edtp4MUzb8cxb673uHbAvZMK9Wa8age3Bq4ei9jaDBZxKbuipL1DkQvkuUzKtz1P6aDWaw7fAOCoaOs/OTobjjFsiI6vwtfL/0mU5yvuUErnCEVMOHCP/+RVMJL0JoNhKCxMARcJ0YnwSDG1tYEabAScaYK2AIABhYukI=
  app: Todo-Terminal
  skip_cleanup: true
